name: Check File Action v2
on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
    inputs:
      filename:
        description: 'CHECK FILE'
        type: string
        required: false
        default: ''
      pattern:
        description: 'CHECK TEXT'
        type: string
        required: false
        default: ''
      rootdir:
        description: 'WORKSPACE'
        type: boolean
        required: false
        default: 'false'
      number:
        description: 'FILE COUNT'
        type: number
        required: false
        default: 0
      update:
        description: 'UPDATE REPO'
        type: boolean
        required: false
        default: 'false'
      report:
        description: 'UPLOAD REPORT'
        type: boolean
        required: false
        default: 'false'
      repair:
        description: 'ERROR REPAIR'
        type: boolean
        required: false
        default: 'false'
      DEVICE_TREE:
        description: 'DEVICE TREE'
        required: true
        default: 'https://github.com/Tec4Sho/android_kernel_mt8163.git'
      DEVICE_TREE_BRANCH:
        description: 'DEVICE TREE BRANCH'
        required: true
        default: 'android-9.0'
      DEVICE_PATH:
        description: 'DEVICE PATH'
        required: true
        default: 'kernel/alps/tb8163p3_bsp'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:  # required for all workflows 
      security-events: write # only required for workflows in private repositories 
      actions: write 
      contents: write
    steps:      
      - name: Create Workspace
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/workspace
          set -o allexport
          export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
          if [[ `which git` ]]; then
          echo -e "\n`git --version`\n";
            git config --global core.longpaths true
            git config --global core.protectNTFS false
            git config --global http.postBuffer 524288000 # Increase post buffer size (example value in bytes)
            git config --global http.lowSpeedLimit 0      # Disable low speed limit
            git config --global http.lowSpeedTime 999999  # Increase low speed time threshold
          else
            echo -e "\nGit needed installing now....\n";
            sudo DEBIAN_FRONTEND=noninteractive sudo apt-get install -yq git >/dev/null;
            git config --global core.longpaths true
            git config --global core.protectNTFS false
            git config --global http.postBuffer 524288000 # Increase post buffer size (example value in bytes)
            git config --global http.lowSpeedLimit 0      # Disable low speed limit
            git config --global http.lowSpeedTime 999999  # Increase low speed time threshold
          fi;
          set +e
        continue-on-error: true
          
      - name: Clone Recovery Repo
        if: steps.restore-workspace-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: ./workspace/${{ github.event.inputs.DEVICE_PATH }}
          ref: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}
          clean: false
          
      - name: Check Workspace
        run: |
          du -h -d 4
          echo
          du . -h -d 6
          
      - name: Check File
        if: inputs.filename != '' || inputs.pattern != ''
        uses: Tec4Sho/check-file-action@v2
        with:
          filename: ${{ inputs.filename }}
          #filetype: .c
          database: true
          pattern: ${{ inputs.pattern }}
          project: true
          dirname: workspace
          content: false
          include: false
          rootdir: ${{ inputs.rootdir }}
          recheck: false
          repair: ${{ inputs.repair }}
          report: ${{ inputs.report }}
          update: ${{ inputs.update }}
          stored: true
          number: ${{ inputs.number }}
        continue-on-error: false
