name: Check File Action Pro
on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
    inputs:
      filename:
        description: 'CHECK FILE'
        type: string
        required: false
        default: ''
      pattern:
        description: 'CHECK TEXT'
        type: string
        required: false
        default: ''
      analyzer:
        description: 'ANALYZER'
        type: choice
        required: false
        default: '1'
        options:
        - 0
        - 1
        - 2
        - 3
        - 4
      number:
        description: 'FILE COUNT'
        type: number
        required: false
        default: '0'
      update:
        description: 'UPDATE REPO'
        type: boolean
        required: false
        default: 'false'
      report:
        description: 'UPLOAD REPORT'
        type: boolean
        required: false
        default: 'false'
      repair:
        description: 'ERROR REPAIR'
        type: boolean
        required: false
        default: 'false'
      DEVICE_TREE:
        description: 'DEVICE TREE'
        required: true
        default: 'https://github.com/Tec4Sho/android_kernel_mt8163.git'
      DEVICE_TREE_BRANCH:
        description: 'DEVICE TREE BRANCH'
        required: true
        default: 'android-9.0'
      DEVICE_PATH:
        description: 'DEVICE PATH'
        required: true
        default: 'kernel/alps/tb8163p3_bsp'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:  # required for all workflows 
      security-events: write # only required for workflows in private repositories 
      actions: write 
      contents: write
    steps:      
      - name: Create Workspace
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/workspace
          set -o allexport
          export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
          if [[ `which git` ]]; then
          echo -e "\n`git --version`\n";
            git config --global core.longpaths true
            git config --global core.protectNTFS false
            git config --global http.postBuffer 524288000 # Increase post buffer size (example value in bytes)
            git config --global http.lowSpeedLimit 0      # Disable low speed limit
            git config --global http.lowSpeedTime 999999  # Increase low speed time threshold
          else
            echo -e "\nGit needed installing now....\n";
            sudo DEBIAN_FRONTEND=noninteractive sudo apt-get install -yq git >/dev/null;
            git config --global core.longpaths true
            git config --global core.protectNTFS false
            git config --global http.postBuffer 524288000 # Increase post buffer size (example value in bytes)
            git config --global http.lowSpeedLimit 0      # Disable low speed limit
            git config --global http.lowSpeedTime 999999  # Increase low speed time threshold
          fi;
          set +e
        continue-on-error: true

     # - name: Cleanup Environment
     #   uses: rokibhasansagar/slimhub_actions@main
     #  with:
     #     retain: "cmake,clang-tidy-*,clang,gcc,g++,python3,batcat,ansi2txt,git,git-repo,git-core,cppcheck,cppcheck-gui,shellcheck,shellharden,checkmake"
          # That's it! Now use your normal steps  
          
      - name: Clone Recovery Repo
        if: steps.restore-workspace-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          path: ./workspace/${{ github.event.inputs.DEVICE_PATH }}
          ref: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}
          clean: true
          fetch-depth: 1
          show-progress: false
          
      - name: Check Workspace
        run: |
          du -h -d 4
          echo
          du . -h -d 6
          
      - name: Check File
        uses: Tec4Sho/check-file-action@v2
        with:
          analyzer: ${{ inputs.analyzer }}
          filename: ${{ inputs.filename }}
          filetype: c
          database: true
          pattern: ${{ inputs.pattern }}
          project: true
          dirname: workspace
          content: false
          include: true
          rootdir: false
          recheck: false
          repair: ${{ inputs.repair }}
          report: ${{ inputs.report }}
          update: ${{ inputs.update }}
          upload: true
          stored: true
          number: ${{ inputs.number }}
          output: 1
          build: 3
        continue-on-error: false

