name: Check File Action Pro
on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
    inputs:
      filename:
        description: 'CHECK FILENAME'
        type: string
        required: false
        default: ''
      pattern:
        description: 'CHECK TEXT STRING'
        type: string
        required: false
        default: ''
      dirname:
        description: 'DEFAULT DIRECTORY'
        type: string
        required: false
        default: ''  
      analyzer:
        description: 'ANALYZER MODE'
        type: choice
        required: false
        default: '0'
        options:
        - 0
        - 1
        - 2
        - 3
        - 4
      build:
        description: 'BUILD MODE'
        type: choice
        required: false
        default: '0'
        options:
        - 0
        - 1
        - 2
        - 3
        - 4  
      number:
        description: 'FILE COUNT LIMIT'
        type: number
        required: false
        default: '0'
      update:
        description: 'UPDATE REPOSITORY'
        type: boolean
        required: false
        default: 'false'
      report:
        description: 'UPLOAD CHECK REPORT'
        type: boolean
        required: false
        default: 'false'
      repair:
        description: 'FILE ERROR REPAIR'
        type: boolean
        required: false
        default: 'false'
      cache:
        description: 'CACHE REPOSITORY'
        type: boolean
        required: false
        default: 'false'
        
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:  # required for all workflows 
      security-events: write # only required for workflows in private repositories 
      actions: write 
      contents: write
    steps:      
      - name: Create Workspace
        run: |
          if [[ `which git` ]]; then
          echo -e "\n`git --version`\n";
            git config --global core.longpaths true
            git config --global core.protectNTFS false
            git config --global http.postBuffer 524288000 # Increase post buffer size (example value in bytes)
            git config --global http.lowSpeedLimit 0      # Disable low speed limit
            git config --global http.lowSpeedTime 999999  # Increase low speed time threshold
          else
            echo -e "\nGit needed installing now....\n";
            sudo DEBIAN_FRONTEND=noninteractive sudo apt-get install -yq git >/dev/null;
            git config --global core.longpaths true
            git config --global core.protectNTFS false
            git config --global http.postBuffer 524288000 # Increase post buffer size (example value in bytes)
            git config --global http.lowSpeedLimit 0      # Disable low speed limit
            git config --global http.lowSpeedTime 999999  # Increase low speed time threshold
          fi;
        continue-on-error: true

     # - name: Cleanup Environment
     #   uses: rokibhasansagar/slimhub_actions@main
     #  with:
     #     retain: "cmake,clang-tidy-*,clang,gcc,g++,python3,batcat,ansi2txt,git,git-repo,git-core,cppcheck,cppcheck-gui,shellcheck,shellharden,checkmake"
          # That's it! Now use your normal steps
          
      - name: Check File
        uses: Tec4Sho/check-file-action@v2
        with:
          analyzer: ${{ inputs.analyzer }}
          makefile: 'omni_tb8163p3_bsp-eng'
          filename: ${{ inputs.filename }}
          filetype: c
          database: true
          absolute: true
          pattern: ${{ inputs.pattern }}
          project: true
          dirname: ${{ inputs.dirname }}
          content: true
          include: true
          recheck: false
          repair: ${{ inputs.repair }}
          report: ${{ inputs.report }}
          update: ${{ inputs.update }}
          upload: true
          stored: true
          number: ${{ inputs.number }}
          output: 1
          build: ${{ inputs.build }}
          clean: true
          cache: ${{ inputs.cache }}
        continue-on-error: false
